# Generated by Django 2.1.11 on 2019-10-02 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('engine', models.IntegerField(choices=[(0, 'Report Bro - PDF')], default=0)),
                ('definition', models.TextField()),
                ('validity_from', models.DateTimeField(blank=True, null=True)),
                ('validity_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_ReportDefinition',
                'managed': True,
            },
        ),
    ]
