# Generated by Django 3.2.15 on 2023-04-10 21:59

import core.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_add_report_right_to_EO'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='legacy_id',
            field=models.UUIDField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='validity_to',
            field=core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True),
        ),
    ]
