# Generated by Django 3.2.18 on 2023-05-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_add_missing_fields_to_django_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedreports',
            options={'managed': True},
        ),
    ]
