# Generated by Django 3.2.16 on 2023-10-06 13:48

from django.db import migrations

from core.utils import insert_role_right_for_system


def add_rights(apps, schema_editor):
    insert_role_right_for_system(64, 131200)  # reports


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_set_managed_to_true'),
    ]

    operations = [
        migrations.RunPython(add_rights),
    ]
